language: node_js
node_js:
- '11'
before_install:
- npm install -g npm@'^5.10.0'
- npm install -g RadonApp/radon-extension-build#$TRAVIS_BRANCH || npm install -g RadonApp/radon-extension-build#develop
install:
- neb travis:install $TRAVIS_BRANCH
- neb package:validate
- git diff --exit-code
script:
- npm run build
- npm run travis:test
- npm run travis:coverage
- npm run travis:lint
- if [ ! -f ./Build/Coverage/lcov.info ]; then exit 1; fi
after_success:
- npm install -g coveralls
- cat ./Build/Coverage/lcov.info | coveralls
deploy:
- provider: releases
  tag_name: $TRAVIS_TAG
  target_commitish: $TRAVIS_COMMIT
  draft: true
  skip_cleanup: true
  api_key:
    secure: VW/SHXDfJCzJHsA83hYDFZlFxIWpsL7Cn0nPXAptyKkMfEYQ+7JL7uJ5sUffkOLwWA1mHXcuFARD6jVgJ85sscmGNq7b+DSIap1e6eEWlpEqYNYfeMNQ4xPwaNHDoGVWzGAjVHUmUV7wzHjAvKNq/mSipucz3OKwssoIK6wtU0tga23r6rmtSTwbONIWEfnVvgX2SQWmo3pqLRyUPy+5eZ9A4s32x8MN6mDoKpnnt8yDL6q4KSB5uITpz4fU5S+JU2ggC3UnRzbU/rk3fgWiohlTjw7DyJkjEwnUCpsQWTsp7A18SW+nfJ0gUvV85dira9AMIcM6KIMIs7Ro+BSs6suMgJ2/LVR7lk7KQb2TucLHyXc/Yg0a+mdt54LTuCX9l3iB9GrKo9AeZHYJ6kKIeSGF3c61a8C4/bUhKabvbnp7es8fXRmTkyyXZlknK7PjOYw5LlQHYQKQYp8lZKG8OMxnz1H9nq9dC6qqhgNwvxQygEFYu4z/LNPMUQt92ZUJDEjGGfuQ6Vk51wtSFJQhJjqMR7n0iVq4XpEuJt/ZY44tzz1LoFuVX5nT92koB6umsg3xjtFuovQzqR1fWT6Wa9z+UWCRvGPVF+xa5q8hpiCUqiYlXZWVI6O4JfL9DZ174gTzdrHFYjif8wxGQXlqnkZ26tHKfpl3WvZzpWSWqkU=
  file_glob: true
  file: Build/Production/Radon*.zip
  on:
    repo: RadonApp/radon-extension-chrome
    tags: true
- provider: bintray
  skip_cleanup: true
  key:
    secure: YPeCHU73TazREdFCfsetbl1xwSIXgIkRmqlroPzg8+9FbyeEoYBH1H374Nrn8uPLSMu2jS52jqCXu3rl7XgiECStok6jvlZz7BiRQzyuHtYrigYs7zBo75vu1LsW2/IXSZZvH2jMXy3fchj/UC/sz4N9+5GMkYLV0NUxYr+CnLCDVJSc9m+EUtnAUu0JuxKQrryOdmMfAythqfv45xqZFJf0ORrt1QROJaL3NE6ybFzmoileiQfH6PzVMN8PPO4lJODDHNCTZbi8l3PA7+pGjmHZ46eE8dcMiy7BN0t5IOPmnMJzGrbTnBXzdQHwcJudeC9nGuOZtQTAqB7u2XuP8QQiLVJLpO0bFUdw6rm1ciMsVuY2M+WebFBXEnSim8B1BgYAbI1V3lZxr2/Y5M9PGYxMPdlBR000NkTwoKkN6OC/pWNHg4VWy/wg4xxRvG77f22XZxeC/pv3MqPv7XLTaVxshf2Fibz6VuIVh6hYxj4Yu1iez+s1sllRPrw9D3nTQKzSN0kakXGIwquCU3JbXR7S9+mLHEvHiIIHy7l13Bha1KrB/phyJF1ru3DAUv7QGctJnUTu72fpFU/ZwYVSLNEWL1GP8/Fs1kOfEq9iYpWubH6HWOoX2+HfymhhLQNsa+amYRtTuRAMmNvQDQkVEBx6RFSVM9sTZA479GZq8KA=
  file: Build/Production/bintray.json
  user: radon-ci
  on:
    repo: RadonApp/radon-extension-chrome
    all_branches: true
